services:

  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
    restart: always
    ports: !reset []


  app-blue:
    image: jchcifpbj/sportsclub:latest

    extends:
      file: docker-compose.yml
      service: app-blue
    restart: always


  app-green:
    image: jchcifpbj/sportsclub:latest

    extends:
      file: docker-compose.yml
      service: app-green
    restart: always

  nginx:
    extends:
      file: docker-compose.yml
      service: nginx
    restart: always

volumes:
  postgres:

networks:
  default:
